### ISSUE TITLE
"Callback was already called" error

### ISSUE THREAD

**Issue by zhuzhenyu** [hexojs/hexo-deployer-ftpsync#6] opened 2015-07-20 15:28 UTC
```
- /tags/index.html uploaded successfuly
- /vendors/fancybox/source/blank.gif uploaded successfuly
- /vendors/fancybox/source/fancybox_loading.gif uploaded successfuly
- /vendors/fancybox/source/fancybox_loading@2x.gif uploaded successfuly
- /vendors/fancybox/source/fancybox_overlay.png uploaded successfuly
ftp.put failed.
Additions failed.
Commit failed.
Commit complete.
/home/deploy/app/nodejs/zhuzhenyu.org/node_modules/hexo-deployer-ftpsync/node_modules/ftpsync/node_modules/async/lib/async.js:43
            if (fn === null) throw new Error("Callback was already called.");
                                   ^
Error: Callback was already called.
    at /home/deploy/app/nodejs/zhuzhenyu.org/node_modules/hexo-deployer-ftpsync/node_modules/ftpsync/node_modules/async/lib/async.js:43:36
    at /home/deploy/app/nodejs/zhuzhenyu.org/node_modules/hexo-deployer-ftpsync/node_modules/ftpsync/node_modules/async/lib/async.js:688:17
    at /home/deploy/app/nodejs/zhuzhenyu.org/node_modules/hexo-deployer-ftpsync/node_modules/ftpsync/node_modules/async/lib/async.js:167:37
    at /home/deploy/app/nodejs/zhuzhenyu.org/node_modules/hexo-deployer-ftpsync/node_modules/ftpsync/lib/ftpsync.js:277:7
    at /home/deploy/app/nodejs/zhuzhenyu.org/node_modules/hexo-deployer-ftpsync/node_modules/ftpsync/node_modules/async/lib/async.js:691:13
    at /home/deploy/app/nodejs/zhuzhenyu.org/node_modules/hexo-deployer-ftpsync/node_modules/ftpsync/node_modules/async/lib/async.js:52:16
    at /home/deploy/app/nodejs/zhuzhenyu.org/node_modules/hexo-deployer-ftpsync/node_modules/ftpsync/node_modules/async/lib/async.js:262:21
    at /home/deploy/app/nodejs/zhuzhenyu.org/node_modules/hexo-deployer-ftpsync/node_modules/ftpsync/node_modules/async/lib/async.js:44:16
    at /home/deploy/app/nodejs/zhuzhenyu.org/node_modules/hexo-deployer-ftpsync/node_modules/ftpsync/node_modules/async/lib/async.js:688:17
    at /home/deploy/app/nodejs/zhuzhenyu.org/node_modules/hexo-deployer-ftpsync/node_modules/ftpsync/node_modules/async/lib/async.js:167:37
    at /home/deploy/app/nodejs/zhuzhenyu.org/node_modules/hexo-deployer-ftpsync/node_modules/ftpsync/lib/ftpsync.js:228:13
    at /home/deploy/app/nodejs/zhuzhenyu.org/node_modules/hexo-deployer-ftpsync/node_modules/ftpsync/node_modules/async/lib/async.js:52:16
    at /home/deploy/app/nodejs/zhuzhenyu.org/node_modules/hexo-deployer-ftpsync/node_modules/ftpsync/node_modules/async/lib/async.js:358:13
    at /home/deploy/app/nodejs/zhuzhenyu.org/node_modules/hexo-deployer-ftpsync/node_modules/ftpsync/node_modules/async/lib/async.js:52:16
    at /home/deploy/app/nodejs/zhuzhenyu.org/node_modules/hexo-deployer-ftpsync/node_modules/ftpsync/node_modules/async/lib/async.js:320:29
    at /home/deploy/app/nodejs/zhuzhenyu.org/node_modules/hexo-deployer-ftpsync/node_modules/ftpsync/node_modules/async/lib/async.js:44:16
    at /home/deploy/app/nodejs/zhuzhenyu.org/node_modules/hexo-deployer-ftpsync/node_modules/ftpsync/node_modules/async/lib/async.js:355:17
    at Socket.<anonymous> (/home/deploy/app/nodejs/zhuzhenyu.org/node_modules/hexo-deployer-ftpsync/node_modules/ftpsync/lib/ftpsync.js:475:13)
    at Socket.f (/home/deploy/app/nodejs/zhuzhenyu.org/node_modules/hexo-deployer-ftpsync/node_modules/ftpsync/node_modules/jsftp/node_modules/once/once.js:16:25)
    at Socket.emit (events.js:107:17)
    at net.js:459:14
    at process._tickCallback (node.js:355:11)
[deploy@Tokyo zhuzhenyu.org]$
```

博主，报了如下错误。

**Comment by evanplaice** [comment] 2016-01-25 07:58
Looks like a dupe of #8

**Comment by peteruhnak** [comment] 2016-08-24 13:14
I just ran into this bug, and the problem for me, was that the server refused my connection (the server has IP-based filtering). Once I enabled my IP the problem went away. So maybe just a better error message? (Failed to establish connection or something).

**Comment by stevenjoezhang** [comment] 2020-04-26 15:45
Closing due to inactivity, please re-open if it is still outstanding.

**Closed by stevenjoezhang** 2020-04-26 15:45 UTC
